name: dharmlok
description: An application for Dharmlok

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_html: ^2.2.1
  syncfusion_flutter_pdfviewer: ^20.3.48
  carousel_slider: ^4.1.1
  google_maps_flutter: ^2.2.1
  quantity_input: ^1.0.2
  url_launcher: ^6.1.6
  intl: ^0.17.0
  location: ^4.4.0
  permission_handler: ^10.1.0
  youtube_player_flutter: ^8.1.1
  youtube_explode_dart: ^1.10.10
  chewie: ^1.3.5
  video_player: ^2.4.7
  audioplayers: ^1.1.1
  flutter_quill: ^6.0.8+1
  quill_markdown: ^0.1.0
  markdown: ^6.0.1
  delta_markdown: ^0.8.0
  flutter_widget_from_html: ^0.8.5
  just_audio: ^0.9.29
  audio_video_progress_bar: ^0.11.0
  fluttertoast: ^8.1.1
  get_time_ago: ^1.1.5
  lottie: ^1.4.2
  scroll_to_index: ^3.0.1
  spritewidget: ^2.0.1
  flutter_image_map: ^0.9.3
  assets_audio_player: ^3.0.6
  wakelock: ^0.6.2
  tutorial_coach_mark: ^1.2.4
  google_sign_in: ^5.4.4
  flutter_signin_button: ^2.0.0
  flutter_login_facebook: ^1.7.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
